Repository Discozavisim/World-of-Darkness-13, pull requests merged in 2025-09, with the labels that each got.

#154 Нерф экспы и перекачей говняненьких
  code/controllers/master.dm
  code/controllers/subsystem/city_time.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_tabs/Char_settings and Charlist.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/vtmb/dharma.dm
Labels: Balance

#157 Фикс специализации атрибутов
  code/modules/client/preferences_savefile.dm
Labels: Fix

#160 Фикс рейджа и сапли технишн фурри
  code/modules/vtmb/jobs/supply_assistant.dm
  code/modules/wod13/blackout.dm
Labels: Feature

#164 Фиксики-фиксики
  .gitignore
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/melee.dm
  code/datums/datacore.dm
  code/datums/martial/police_jiu.dm
  code/game/machinery/limbgrower.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/client/zheadshot_cumshot.dm
  code/modules/jobs/jobs.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/research/designs/limbgrower_designs.dm
  code/modules/vtmb/artifacts.dm
  code/modules/vtmb/disciplines/obfuscate.dm
  code/modules/vtmb/disciplines/vicissitude.dm
  code/modules/vtmb/gridventory.dm
  code/modules/vtmb/jobs/jobs.dm
  code/modules/vtmb/jobs/police.dm
  code/modules/vtmb/jobs/priest.dm
  code/modules/vtmb/jobs/scourge.dm
  code/modules/vtmb/paths/_paths.dm
  code/modules/vtmb/paths/humanity.dm
  code/modules/vtmb/rolling.dm
  code/modules/wod13/car.dm
  code/modules/wod13/clothcode.dm
  code/modules/wod13/food.dm
  code/modules/wod13/guns.dm
  code/modules/wod13/melee.dm
  html/admin/banpanel.css
  tgstation.dme
Labels: Fix, Feature, Map Edit, Config Update, Code Improvement

#165 Быстрые фиксы мелких багов
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/jobs/garou/poisonshore.dm
  code/modules/wod13/lombard.dm
Labels: Fix, Map Edit
